/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment.part.tdd;

public class App {
  /**
   * Application starting point.
   *
   * @param args command line arguments.
   */
  public static void main(String[] args) {
    UserInterface ui = new UserInterface();
  }
}
