/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment.part.tdd;

import java.util.Scanner;

public class App {
  /**
   * Application starting point.
   *
   * @param args command line arguments.
   */
  public static void main(String[] args) {
    UserInterface ui = new UserInterface();
    Die dieOne = new Die();
    Die dieTwo = new Die();
    DiceGame diceGame = new DiceGame(dieOne, dieTwo);
    Player player = new Player(ui, new Scanner(System.in), diceGame);

    player.playGame();
  }
}
